### ISSUE TITLE
Auth server use HTTPS

### ISSUE THREAD

**Issue by blling** [serlesen/authorization-server#1]
if the `issuer-uri` use `https`, then how to config?

**Comment by serlesen** [comment]
You can add the protocol in the field `issuer-uri` as following:
```
spring:
  application.name: backend-client
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: https://backend-auth:8081
```
